insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("D'Artagnan", "Marlin", 8.99, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Bambino", "Tubarão tigre", 21.49, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Larapio", "Peixe Bagre", 2.40, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Leoncio", "Leão Marinho", 44.99, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Sombrero", "Água viva caribenha", 0.44, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Fofucha", "Baleia Jubarte", 1012.99, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Leila", "Siri", 0.99, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Laura", "Baleia Branca", 1021.99, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Naruto", "Tubarão Raposa", 12.99, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Coisinha", "Peixe pedra", 2.99, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Gari", "Peixe beta", 0.99, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Zildo", "Anemona", 4.29, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Marli", "Enguia", 1.99, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Jonas", "Atum", 20.99, false, true);
insert into tb_petshop(nome, raça, peso, agressivo, ativo) values ("Willy", "Baleia Orca", 600.99, false, true);
